FROM python:3.11.1

WORKDIR /Major Project frontend/login_sys/views/app

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . .

CMD ["python","Major Project frontend/login_sys/views/app ","app.main:app", "--host", "0.0.0.0", "--port", "7860"]

RUN chown -R 42420:42420 /Major Project frontend/login_sys/views/app

ENV HOME=/Major Project frontend/login_sys/views/app

